export azur from './color/azur.jpg';
export azur from './color/azur.jpg';
export beige from './color/beige.jpg';
export blue from './color/blue.jpg';
export burgundy from './color/burgundy.jpg';
export grey from './color/grey.jpg';
export orange from './color/orange.jpg';
export purple from './color/purple.jpg';
export violet from './color/violet.jpg';
export yellow from './color/yellow.jpg';
export black from './color/black.jpg';
export brown from './color/brown.jpg';
export green from './color/green.jpg';
export olive from './color/olive.jpg';
export pink from './color/pink.jpg';
export red from './color/red.jpg';
export white from './color/white.jpg';
export clearing from './weather/clearing.jpg';
export darkening from './weather/darkening.jpg';
export moon from './weather/moon.jpg';
export rain from './weather/rain.jpg';
export snow from './weather/snow.jpg';
export storm from './weather/storm.jpg';
export sunrise from './weather/sunrise.jpg';
export unstable from './weather/unstable.jpg';
export clouds from './weather/clouds.jpg';
export fog from './weather/fog.jpg';
export moonset from './weather/moonset.jpg';
export sky from './weather/sky.jpg';
export stars from './weather/stars.jpg';
export sun from './weather/sun.jpg';
export sunset from './weather/sunset.jpg';
export wind from './weather/wind.jpg';
export bathroom from './where-in/bathroom.jpg'
export carpet from   './where-in/carpet.jpg'
export column from   './where-in/column.jpg'
export door from   './where-in/door.jpg'
export kitchen from   './where-in/kitchen.jpg'
export lock from   './where-in/lock.jpg'
export stairs from   './where-in/stairs.jpg'
export toilet from   './where-in/toilet.jpg'
export bedroom from   './where-in/bedroom.jpg'
export chair from   './where-in/chair.jpg'
export handle from   './where-in/doorhandle.jpg'
export fireplace from   './where-in/fireplace.jpg'
export lamp from   './where-in/lamp.jpg'
export mirror from   './where-in/mirror.jpg'
export table from   './where-in/table.jpg'
export window from   './where-in/window.jpg'
export bridge from'./where-out/bridge.jpg'
export cave from  './where-out/cave.jpg'
export city from  './where-out/city.jpg'
export island from  './where-out/island.jpg'
export mountains from  './where-out/mountains.jpg'
export school from  './where-out/school.jpg'
export trail from  './where-out/trail.jpg'
export valley from  './where-out/valley.jpg'
export castle from  './where-out/castle.jpg'
export church from  './where-out/church.jpg'
export garden from  './where-out/garden.jpg'
export metro from  './where-out/metro.jpg'
export river from  './where-out/river.jpg'
export sea from  './where-out/sea.jpg'
export tunnel from  './where-out/tunnel.jpg'
export well from  './where-out/well.jpg'
export blade from'./what-in/blade.jpg'
export chain from  './what-in/chain.jpg'
export cradle from  './what-in/cradle.jpg'
export game from  './what-in/game.jpg'
export money from  './what-in/money.jpg'
export purse from  './what-in/purse.jpg'
export scissors from  './what-in/scissors.jpg'
export tools from  './what-in/tools.jpg'
export books from  './what-in/books.jpg'
export comb from  './what-in/comb.jpg'
export flower from  './what-in/flower.jpg'
export key from  './what-in/key.jpg'
export necklace from  './what-in/necklace.jpg'
export ring from  './what-in/ring.jpg'
export shoe from  './what-in/shoe.jpg'
export umbrella from  './what-in/umbrella.jpg'
export airplane from'./what-out/airplane.jpg'
export boat from  './what-out/boat.jpg'
export drums from  './what-out/drums.jpg'
export fountain from  './what-out/fountain.jpg'
export mushroom from  './what-out/mushroom.jpg'
export shell from  './what-out/shell.jpg'
export trumpet from  './what-out/trumpet.jpg'
export waterfall from  './what-out/waterfall.jpg'
export bicycle from  './what-out/bicycle.jpg'
export car from  './what-out/car.jpg'
export egg from  './what-out/egg.jpg'
export gun from  './what-out/gun.jpg'
export roots from  './what-out/roots.jpg'
export train from  './what-out/train.jpg'
export veil from  './what-out/veil.jpg'
export wheel from  './what-out/wheel.jpg'
export arm from'./body/arm.jpg'
export breast from  './body/breast.jpg'
export eye from  './body/eye.jpg'
export foot from  './body/foot.jpg'
export hand from  './body/hand.jpg'
export moustache from  './body/moustache.jpg'
export nail from  './body/nail.jpg'
export tongue from  './body/tongue.jpg'
export bones from  './body/bones.jpg'
export ear from  './body/ear.jpg'
export finger from  './body/finger.jpg'
export hair from  './body/hair.jpg'
export head from  './body/head.jpg'
export mouth from  './body/mouth.jpg'
export nose from  './body/nose.jpg'
export tooth from  './body/tooth.jpg'
export ant from'./animals/ant.jpg'
export butterfly from  './animals/butterfly.jpg'
export dog from  './animals/dog.jpg'
export fish from  './animals/fish.jpg'
export fox from  './animals/fox.jpg'
export lion from  './animals/lion.jpg'
export rabbit from  './animals/rabbit.jpg'
export roach from  './animals/roach.jpg'
export bee from  './animals/bee.jpg'
export cat from  './animals/cat.jpg'
export eagle from  './animals/eagle.jpg'
export fly from  './animals/fly.jpg'
export horse from  './animals/horse.jpg'
export monkey from  './animals/monkey.jpg'
export rat from  './animals/rat.jpg'
export snake from  './animals/snake.jpg'
export img11aIN from "./meaning_symbols/11aIN.png"
export img12aIN from   "./meaning_symbols/12aIN.png"
export img13aIN from   "./meaning_symbols/13aIN.png"
export img14aIN from   "./meaning_symbols/14aIN.png"
export img21aIN from   "./meaning_symbols/21aIN.png"
export img22aIN from   "./meaning_symbols/22aIN.png"
export img23aIN from   "./meaning_symbols/23aIN.png"
export img24aIN from   "./meaning_symbols/24aIN.png"
export img31aIN from   "./meaning_symbols/31aIN.png"
export img32aIN from   "./meaning_symbols/32aIN.png"
export img33aIN from   "./meaning_symbols/33aIN.png"
export img34aIN from   "./meaning_symbols/34aIN.png"
export img41aIN from   "./meaning_symbols/41aIN.png"
export img42aIN from   "./meaning_symbols/42aIN.png"
export img43aIN from   "./meaning_symbols/43aIN.png"
export img44aIN from   "./meaning_symbols/44aIN.png"
export img11aOUT from   "./meaning_symbols/11aOUT.png"
export img12aOUT from   "./meaning_symbols/12aOUT.png"
export img13aOUT from   "./meaning_symbols/13aOUT.png"
export img14aOUT from   "./meaning_symbols/14aOUT.png"
export img21aOUT from   "./meaning_symbols/21aOUT.png"
export img22aOUT from   "./meaning_symbols/22aOUT.png"
export img23aOUT from   "./meaning_symbols/23aOUT.png"
export img24aOUT from   "./meaning_symbols/24aOUT.png"
export img31aOUT from   "./meaning_symbols/31aOUT.png"
export img32aOUT from   "./meaning_symbols/32aOUT.png"
export img33aOUT from   "./meaning_symbols/33aOUT.png"
export img34aOUT from   "./meaning_symbols/34aOUT.png"
export img41aOUT from   "./meaning_symbols/41aOUT.png"
export img42aOUT from   "./meaning_symbols/42aOUT.png"
export img43aOUT from   "./meaning_symbols/43aOUT.png"
export img44aOUT from   "./meaning_symbols/44aOUT.png"
export img11bIN from   "./meaning_symbols/11bIN.png"
export img12bIN from   "./meaning_symbols/12bIN.png"
export img13bIN from   "./meaning_symbols/13bIN.png"
export img14bIN from   "./meaning_symbols/14bIN.png"
export img21bIN from   "./meaning_symbols/21bIN.png"
export img22bIN from   "./meaning_symbols/22bIN.png"
export img23bIN from   "./meaning_symbols/23bIN.png"
export img24bIN from   "./meaning_symbols/24bIN.png"
export img31bIN from   "./meaning_symbols/31bIN.png"
export img32bIN from   "./meaning_symbols/32bIN.png"
export img33bIN from   "./meaning_symbols/33bIN.png"
export img34bIN from   "./meaning_symbols/34bIN.png"
export img41bIN from   "./meaning_symbols/41bIN.png"
export img42bIN from   "./meaning_symbols/42bIN.png"
export img43bIN from   "./meaning_symbols/43bIN.png"
export img44bIN from   "./meaning_symbols/44bIN.png"
export img11bOUT from   "./meaning_symbols/11bOUT.png"
export img12bOUT from   "./meaning_symbols/12bOUT.png"
export img13bOUT from   "./meaning_symbols/13bOUT.png"
export img14bOUT from   "./meaning_symbols/14bOUT.png"
export img21bOUT from   "./meaning_symbols/21bOUT.png"
export img22bOUT from   "./meaning_symbols/22bOUT.png"
export img23bOUT from   "./meaning_symbols/23bOUT.png"
export img24bOUT from   "./meaning_symbols/24bOUT.png"
export img31bOUT from   "./meaning_symbols/31bOUT.png"
export img32bOUT from   "./meaning_symbols/32bOUT.png"
export img33bOUT from   "./meaning_symbols/33bOUT.png"
export img34bOUT from   "./meaning_symbols/34bOUT.png"
export img41bOUT from   "./meaning_symbols/41bOUT.png"
export img42bOUT from   "./meaning_symbols/42bOUT.png"
export img43bOUT from   "./meaning_symbols/43bOUT.png"
export img44bOUT from   "./meaning_symbols/44bOUT.png"
export img11cIN from   "./meaning_symbols/11cIN.png"
export img12cIN from   "./meaning_symbols/12cIN.png"
export img13cIN from   "./meaning_symbols/13cIN.png"
export img14cIN from   "./meaning_symbols/14cIN.png"
export img21cIN from   "./meaning_symbols/21cIN.png"
export img22cIN from   "./meaning_symbols/22cIN.png"
export img23cIN from   "./meaning_symbols/23cIN.png"
export img24cIN from   "./meaning_symbols/24cIN.png"
export img31cIN from   "./meaning_symbols/31cIN.png"
export img32cIN from   "./meaning_symbols/32cIN.png"
export img33cIN from   "./meaning_symbols/33cIN.png"
export img34cIN from   "./meaning_symbols/34cIN.png"
export img41cIN from   "./meaning_symbols/41cIN.png"
export img42cIN from   "./meaning_symbols/42cIN.png"
export img43cIN from   "./meaning_symbols/43cIN.png"
export img44cIN from   "./meaning_symbols/44cIN.png"
export img11cOUT from   "./meaning_symbols/11cOUT.png"
export img12cOUT from   "./meaning_symbols/12cOUT.png"
export img13cOUT from   "./meaning_symbols/13cOUT.png"
export img14cOUT from   "./meaning_symbols/14cOUT.png"
export img21cOUT from   "./meaning_symbols/21cOUT.png"
export img22cOUT from   "./meaning_symbols/22cOUT.png"
export img23cOUT from   "./meaning_symbols/23cOUT.png"
export img24cOUT from   "./meaning_symbols/24cOUT.png"
export img31cOUT from   "./meaning_symbols/31cOUT.png"
export img32cOUT from   "./meaning_symbols/32cOUT.png"
export img33cOUT from   "./meaning_symbols/33cOUT.png"
export img34cOUT from   "./meaning_symbols/34cOUT.png"
export img41cOUT from   "./meaning_symbols/41cOUT.png"
export img42cOUT from   "./meaning_symbols/42cOUT.png"
export img43cOUT from   "./meaning_symbols/43cOUT.png"
export img44cOUT from   "./meaning_symbols/44cOUT.png"
export img11dIN from   "./meaning_symbols/11dIN.png"
export img12dIN from   "./meaning_symbols/12dIN.png"
export img13dIN from   "./meaning_symbols/13dIN.png"
export img14dIN from   "./meaning_symbols/14dIN.png"
export img21dIN from   "./meaning_symbols/21dIN.png"
export img22dIN from "./meaning_symbols/22dIN.png"
export img23dIN from "./meaning_symbols/23dIN.png"
export img24dIN from "./meaning_symbols/24dIN.png"
export img31dIN from "./meaning_symbols/31dIN.png"
export img32dIN from "./meaning_symbols/32dIN.png"
export img33dIN from "./meaning_symbols/33dIN.png"
export img34dIN from "./meaning_symbols/34dIN.png"
export img41dIN from "./meaning_symbols/41dIN.png"
export img42dIN from "./meaning_symbols/42dIN.png"
export img43dIN from "./meaning_symbols/43dIN.png"
export img44dIN from "./meaning_symbols/44dIN.png"
export img11dOUT from "./meaning_symbols/11dOUT.png"
export img12dOUT from "./meaning_symbols/12dOUT.png"
export img13dOUT from "./meaning_symbols/13dOUT.png"
export img14dOUT from "./meaning_symbols/14dOUT.png"
export img21dOUT from "./meaning_symbols/21dOUT.png"
export img22dOUT from "./meaning_symbols/22dOUT.png"
export img23dOUT from "./meaning_symbols/23dOUT.png"
export img24dOUT from "./meaning_symbols/24dOUT.png"
export img31dOUT from "./meaning_symbols/31dOUT.png"
export img32dOUT from "./meaning_symbols/32dOUT.png"
export img33dOUT from "./meaning_symbols/33dOUT.png"
export img34dOUT from "./meaning_symbols/34dOUT.png"
export img41dOUT from "./meaning_symbols/41dOUT.png"
export img42dOUT from "./meaning_symbols/42dOUT.png"
export img43dOUT from "./meaning_symbols/43dOUT.png"
export img44dOUT from "./meaning_symbols/44dOUT.png"
export img11eIN from "./meaning_symbols/11eIN.png"
export img12eIN from "./meaning_symbols/12eIN.png"
export img13eIN from "./meaning_symbols/13eIN.png"
export img14eIN from "./meaning_symbols/14eIN.png"
export img21eIN from "./meaning_symbols/21eIN.png"
export img22eIN from "./meaning_symbols/22eIN.png"
export img23eIN from "./meaning_symbols/23eIN.png"
export img24eIN from "./meaning_symbols/24eIN.png"
export img31eIN from "./meaning_symbols/31eIN.png"
export img32eIN from "./meaning_symbols/32eIN.png"
export img33eIN from "./meaning_symbols/33eIN.png"
export img34eIN from "./meaning_symbols/34eIN.png"
export img41eIN from "./meaning_symbols/41eIN.png"
export img42eIN from "./meaning_symbols/42eIN.png"
export img43eIN from "./meaning_symbols/43eIN.png"
export img44eIN from "./meaning_symbols/44eIN.png"
export img11eOUT from "./meaning_symbols/11eOUT.png"
export img12eOUT from "./meaning_symbols/12eOUT.png"
export img13eOUT from "./meaning_symbols/13eOUT.png"
export img14eOUT from "./meaning_symbols/14eOUT.png"
export img21eOUT from "./meaning_symbols/21eOUT.png"
export img22eOUT from "./meaning_symbols/22eOUT.png"
export img23eOUT from "./meaning_symbols/23eOUT.png"
export img24eOUT from "./meaning_symbols/24eOUT.png"
export img31eOUT from "./meaning_symbols/31eOUT.png"
export img32eOUT from "./meaning_symbols/32eOUT.png"
export img33eOUT from "./meaning_symbols/33eOUT.png"
export img34eOUT from "./meaning_symbols/34eOUT.png"
export img41eOUT from "./meaning_symbols/41eOUT.png"
export img42eOUT from "./meaning_symbols/42eOUT.png"
export img43eOUT from "./meaning_symbols/43eOUT.png"
export img44eOUT from "./meaning_symbols/44eOUT.png"
export imgin from "./where/in.png"
export imgquestionMark from "./where/questionMark.png"
export imgout from "./where/out.png"
export musicSymbol from "./other/music-symbol.png.png"
export paintingSymbol from "./other/painting-symbol.png.png"